export const CARTORDER_LIST_REQUEST = "CARTORDER_LIST_REQUEST";
export const CARTORDER_LIST_SUCCESS = "CARTORDER_LIST_SUCCESS";
export const CARTORDER_LIST_FAIL = "CARTORDER_LIST_FAIL";

export const CARTORDER_DETAILS_REQUEST = "CARTORDER_DETAILS_REQUEST";
export const CARTORDER_DETAILS_SUCCESS = "CARTORDER_DETAILS_SUCCESS";
export const CARTORDER_DETAILS_FAIL = "CARTORDER_DETAILS_FAIL";

export const CARTORDER_DELIVERED_REQUEST = "CARTORDER_DELIVERED_REQUEST";
export const CARTORDER_DELIVERED_SUCCESS = "CARTORDER_DELIVERED_SUCCESS";
export const CARTORDER_DELIVERED_FAIL = "CARTORDER_DELIVERED_FAIL";
export const CARTORDER_DELIVERED_RESET = "CARTORDER_DELIVERED_RESET";

export const CARTORDER_APPROVED_REQUEST = "CARTORDER_APPROVED_REQUEST";
export const CARTORDER_APPROVED_SUCCESS = "CARTORDER_APPROVED_SUCCESS";
export const CARTORDER_APPROVED_FAIL = "CARTORDER_APPROVED_FAIL";
export const CARTORDER_APPROVED_RESET = "CARTORDER_APPROVED_RESET";

export const CARTORDER_DELETE_REQUEST = "CARTORDER_DELETE_REQUEST";
export const CARTORDER_DELETE_SUCCESS = "CARTORDER_DELETE_SUCCESS";
export const CARTORDER_DELETE_FAIL = "CARTORDER_DELETE_FAIL";

export const CARTORDER_UPDATE_RESET = "CARTORDER_UPDATE_RESET";